export const STATES = Object.freeze({
  IDLE: 'IDLE',

  ONBOARDING_START: 'ONBOARDING_START',
  ENTER_MANAGER_PIN: 'ENTER_MANAGER_PIN',
  ONBOARDING_ENTER_NAME: 'ONBOARDING_ENTER_NAME',

  // Admin
  ADMIN_MENU: 'ADMIN_MENU',
  ADMIN_OBJECTS_LIST: 'ADMIN_OBJECTS_LIST',
  ADMIN_OBJECT_DETAILS: 'ADMIN_OBJECT_DETAILS',
  ADMIN_OBJECT_REASSIGN: 'ADMIN_OBJECT_REASSIGN',
  ADMIN_OBJECT_EMPLOYEES_LIST: 'ADMIN_OBJECT_EMPLOYEES_LIST',
  ADMIN_OBJECT_EMPLOYEE_ONBOARD: 'ADMIN_OBJECT_EMPLOYEE_ONBOARD',
  ADMIN_EMPLOYEES_LIST: 'ADMIN_EMPLOYEES_LIST',

  // Manager
  MANAGER_MENU: 'MANAGER_MENU',
  MANAGER_OBJECTS_LIST: 'MANAGER_OBJECTS_LIST',
  MANAGER_EMPLOYEES_LIST: 'MANAGER_EMPLOYEES_LIST',
  MANAGER_EMPLOYEE_CREATE_ENTER_NAME: 'MANAGER_EMPLOYEE_CREATE_ENTER_NAME',
  MANAGER_OBJECT_EMPLOYEE_ONBOARD: 'MANAGER_OBJECT_EMPLOYEE_ONBOARD',
  OBJECT_CREATE_ENTER_NAME: 'OBJECT_CREATE_ENTER_NAME',
  OBJECT_CREATE_ENTER_SCHEDULE: 'OBJECT_CREATE_ENTER_SCHEDULE',
  OBJECT_DETAILS: 'OBJECT_DETAILS',
  OBJECT_EDIT: 'OBJECT_EDIT',
  OBJECT_EDIT_SCHEDULE: 'OBJECT_EDIT_SCHEDULE',
  OBJECT_EDIT_STATUS: 'OBJECT_EDIT_STATUS',
  OBJECT_EMPLOYEES_LIST: 'OBJECT_EMPLOYEES_LIST',
  EMPLOYEE_CREATE_ENTER_NAME: 'EMPLOYEE_CREATE_ENTER_NAME',
  EMPLOYEE_DETAILS: 'EMPLOYEE_DETAILS',
  EMPLOYEE_EDIT_TIME: 'EMPLOYEE_EDIT_TIME',
  WORK_LOG_DETAILS: 'WORK_LOG_DETAILS',
  WORK_LOG_EDIT: 'WORK_LOG_EDIT',
  WORK_LOG_CREATE: 'WORK_LOG_CREATE',
  OBJECT_EMPLOYEE_WORK_LOGS: 'OBJECT_EMPLOYEE_WORK_LOGS',

  // Object Shifts Management
  OBJECT_SHIFTS_LIST: 'OBJECT_SHIFTS_LIST',
  OBJECT_SHIFT_DETAILS: 'OBJECT_SHIFT_DETAILS',
  OBJECT_SHIFT_CONFIRM_START: 'OBJECT_SHIFT_CONFIRM_START',
  OBJECT_SHIFT_CONFIRM_END: 'OBJECT_SHIFT_CONFIRM_END',
  OBJECT_SHIFT_CREATE: 'OBJECT_SHIFT_CREATE',
  OBJECT_SHIFT_REPORT: 'OBJECT_SHIFT_REPORT',
  SHIFT_ADD_EMPLOYEE: 'SHIFT_ADD_EMPLOYEE',
  SHIFT_REMOVE_EMPLOYEE: 'SHIFT_REMOVE_EMPLOYEE',

  // Shifts (Legacy - для обратной совместимости)
  SHIFT_START_CONFIRMATION: 'SHIFT_START_CONFIRMATION',
  SHIFT_START_MARK_ABSENT: 'SHIFT_START_MARK_ABSENT',
  SHIFT_START_ENTER_ABSENT_IDS: 'SHIFT_START_ENTER_ABSENT_IDS',
  SHIFT_END_CONFIRMATION: 'SHIFT_END_CONFIRMATION',
  SHIFT_END_MARK_OVERTIME: 'SHIFT_END_MARK_OVERTIME',
  SHIFT_END_ENTER_OVERTIME_IDS: 'SHIFT_END_ENTER_OVERTIME_IDS',
  SHIFT_END_ENTER_OVERTIME_TIME: 'SHIFT_END_ENTER_OVERTIME_TIME',

  // Employee
  EMPLOYEE_MENU: 'EMPLOYEE_MENU',
  EMPLOYEE_REF_LINK_ACTIVATE: 'EMPLOYEE_REF_LINK_ACTIVATE',

  // Legacy (для обратной совместимости)
  CREATE_OBJECT_ENTER_NAME: 'CREATE_OBJECT_ENTER_NAME',
  SHIFT_SELECT_OBJECT: 'SHIFT_SELECT_OBJECT',
  SHIFT_SELECT_DATE: 'SHIFT_SELECT_DATE',
  SHIFT_ENTER_TIME: 'SHIFT_ENTER_TIME'
});
