export const STATES = Object.freeze({
  IDLE: 'IDLE',

  ONBOARDING_ENTER_NAME: 'ONBOARDING_ENTER_NAME',

  MANAGER_MENU: 'MANAGER_MENU',

  EMPLOYEE_MENU: 'EMPLOYEE_MENU',

  CREATE_OBJECT_ENTER_NAME: 'CREATE_OBJECT_ENTER_NAME',

  SHIFT_SELECT_OBJECT: 'SHIFT_SELECT_OBJECT',
  SHIFT_SELECT_DATE: 'SHIFT_SELECT_DATE',
  SHIFT_ENTER_TIME: 'SHIFT_ENTER_TIME'
});
