import { STATES } from './states.js';

export const TRANSITIONS = Object.freeze({
  [STATES.IDLE]: [
    STATES.ONBOARDING_ENTER_NAME,
    STATES.MANAGER_MENU,
    STATES.EMPLOYEE_MENU
  ],

  [STATES.ONBOARDING_ENTER_NAME]: [
    STATES.MANAGER_MENU
  ],

  [STATES.MANAGER_MENU]: [
    STATES.CREATE_OBJECT_ENTER_NAME,
    STATES.SHIFT_SELECT_OBJECT,
    STATES.IDLE
  ],

  [STATES.CREATE_OBJECT_ENTER_NAME]: [
    STATES.MANAGER_MENU
  ],

  [STATES.SHIFT_SELECT_OBJECT]: [
    STATES.SHIFT_SELECT_DATE
  ],

  [STATES.SHIFT_SELECT_DATE]: [
    STATES.SHIFT_ENTER_TIME
  ],

  [STATES.SHIFT_ENTER_TIME]: [
    STATES.MANAGER_MENU
  ]
});
