import { STATES } from './states.js';

export const TRANSITIONS = Object.freeze({
  [STATES.IDLE]: [
    STATES.ENTER_MANAGER_PIN,
    STATES.ONBOARDING_ENTER_NAME,
    STATES.MANAGER_MENU,
    STATES.EMPLOYEE_MENU,
    STATES.ADMIN_MENU,
    STATES.EMPLOYEE_REF_LINK_ACTIVATE
  ],

  [STATES.ONBOARDING_START]: [
    STATES.ENTER_MANAGER_PIN,
    STATES.ONBOARDING_ENTER_NAME,
  ], 
  [STATES.ENTER_MANAGER_PIN]: [
    STATES.ONBOARDING_ENTER_NAME,
    STATES.IDLE
  ],

  [STATES.ONBOARDING_ENTER_NAME]: [
    STATES.MANAGER_MENU,
    STATES.ADMIN_MENU
  ],

  // Admin
  [STATES.ADMIN_MENU]: [
    STATES.ADMIN_OBJECTS_LIST,
    STATES.ADMIN_EMPLOYEES_LIST,
    STATES.IDLE
  ],

  [STATES.ADMIN_OBJECTS_LIST]: [
    STATES.ADMIN_MENU,
    STATES.ADMIN_OBJECT_DETAILS
  ],

  [STATES.ADMIN_OBJECT_DETAILS]: [
    STATES.ADMIN_OBJECTS_LIST,
    STATES.ADMIN_EMPLOYEES_LIST
  ],

  [STATES.ADMIN_EMPLOYEES_LIST]: [
    STATES.ADMIN_MENU
  ],

  // Manager
  [STATES.MANAGER_MENU]: [
    STATES.MANAGER_OBJECTS_LIST,
    STATES.IDLE
  ],

  [STATES.MANAGER_OBJECTS_LIST]: [
    STATES.OBJECT_CREATE_ENTER_NAME,
    STATES.OBJECT_DETAILS,
    STATES.MANAGER_MENU
  ],

  [STATES.OBJECT_CREATE_ENTER_NAME]: [
    STATES.OBJECT_CREATE_ENTER_SCHEDULE,
    STATES.MANAGER_OBJECTS_LIST
  ],

  [STATES.OBJECT_CREATE_ENTER_SCHEDULE]: [
    STATES.MANAGER_OBJECTS_LIST
  ],

  [STATES.OBJECT_DETAILS]: [
    STATES.OBJECT_EMPLOYEES_LIST,
    STATES.OBJECT_EDIT,
    STATES.MANAGER_OBJECTS_LIST
  ],

  [STATES.OBJECT_EDIT]: [
    STATES.OBJECT_DETAILS,
    STATES.OBJECT_EDIT_SCHEDULE,
    STATES.OBJECT_EDIT_STATUS,
  ],

  [STATES.OBJECT_EDIT_SCHEDULE]: [
    STATES.OBJECT_DETAILS,
    STATES.OBJECT_EDIT,
  ],

  [STATES.OBJECT_EDIT_STATUS]: [
    STATES.OBJECT_DETAILS,
    STATES.OBJECT_EDIT,
  ],

  [STATES.OBJECT_EMPLOYEES_LIST]: [
    STATES.EMPLOYEE_CREATE_ENTER_NAME,
    STATES.EMPLOYEE_DETAILS,
    STATES.OBJECT_DETAILS
  ],

  [STATES.EMPLOYEE_CREATE_ENTER_NAME]: [
    STATES.OBJECT_EMPLOYEES_LIST
  ],

  [STATES.EMPLOYEE_DETAILS]: [
    STATES.EMPLOYEE_EDIT_TIME,
    STATES.OBJECT_EMPLOYEES_LIST
  ],

  [STATES.EMPLOYEE_EDIT_TIME]: [
    STATES.EMPLOYEE_DETAILS
  ],

  // Shifts
  [STATES.SHIFT_START_CONFIRMATION]: [
    STATES.SHIFT_START_MARK_ABSENT,
    STATES.MANAGER_MENU
  ],

  [STATES.SHIFT_START_MARK_ABSENT]: [
    STATES.SHIFT_START_ENTER_ABSENT_IDS
  ],

  [STATES.SHIFT_START_ENTER_ABSENT_IDS]: [
    STATES.MANAGER_MENU
  ],

  [STATES.SHIFT_END_CONFIRMATION]: [
    STATES.SHIFT_END_MARK_OVERTIME,
    STATES.MANAGER_MENU
  ],

  [STATES.SHIFT_END_MARK_OVERTIME]: [
    STATES.SHIFT_END_ENTER_OVERTIME_IDS
  ],

  [STATES.SHIFT_END_ENTER_OVERTIME_IDS]: [
    STATES.SHIFT_END_ENTER_OVERTIME_TIME
  ],

  [STATES.SHIFT_END_ENTER_OVERTIME_TIME]: [
    STATES.MANAGER_MENU
  ],

  // Employee
  [STATES.EMPLOYEE_MENU]: [
    STATES.IDLE
  ],

  [STATES.EMPLOYEE_REF_LINK_ACTIVATE]: [
    STATES.EMPLOYEE_MENU
  ],

  // Legacy (для обратной совместимости)
  [STATES.CREATE_OBJECT_ENTER_NAME]: [
    STATES.MANAGER_MENU
  ],

  [STATES.SHIFT_SELECT_OBJECT]: [
    STATES.SHIFT_SELECT_DATE
  ],

  [STATES.SHIFT_SELECT_DATE]: [
    STATES.SHIFT_ENTER_TIME
  ],

  [STATES.SHIFT_ENTER_TIME]: [
    STATES.MANAGER_MENU
  ]
});
